// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: ziyunix/core/hls.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分片配置
type Hls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 设置切片的间隔
	// @gotags: default:"45s"
	Duration *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty" default:"45s"`
	// 参数设置播放列表保存的最多条目，设置为0会保存有切片信息
	// ffmpeg默认为5，所以只获得最后的5个片段
	// 但是这儿不能设置默认值，保持为0，保存所有切片信息
	Size int32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Hls) Reset() {
	*x = Hls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ziyunix_core_hls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hls) ProtoMessage() {}

func (x *Hls) ProtoReflect() protoreflect.Message {
	mi := &file_ziyunix_core_hls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hls.ProtoReflect.Descriptor instead.
func (*Hls) Descriptor() ([]byte, []int) {
	return file_ziyunix_core_hls_proto_rawDescGZIP(), []int{0}
}

func (x *Hls) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Hls) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_ziyunix_core_hls_proto protoreflect.FileDescriptor

var file_ziyunix_core_hls_proto_rawDesc = []byte{
	0x0a, 0x16, 0x7a, 0x69, 0x79, 0x75, 0x6e, 0x69, 0x78, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x68,
	0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x7a, 0x69, 0x79, 0x75, 0x6e, 0x69,
	0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x03, 0x48, 0x6c, 0x73, 0x12, 0x35, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x32, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e,
	0x7a, 0x69, 0x79, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x1c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x79, 0x75, 0x6e,
	0x69, 0x78, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ziyunix_core_hls_proto_rawDescOnce sync.Once
	file_ziyunix_core_hls_proto_rawDescData = file_ziyunix_core_hls_proto_rawDesc
)

func file_ziyunix_core_hls_proto_rawDescGZIP() []byte {
	file_ziyunix_core_hls_proto_rawDescOnce.Do(func() {
		file_ziyunix_core_hls_proto_rawDescData = protoimpl.X.CompressGZIP(file_ziyunix_core_hls_proto_rawDescData)
	})
	return file_ziyunix_core_hls_proto_rawDescData
}

var file_ziyunix_core_hls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ziyunix_core_hls_proto_goTypes = []interface{}{
	(*Hls)(nil),                 // 0: ziyunix.core.Hls
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_ziyunix_core_hls_proto_depIdxs = []int32{
	1, // 0: ziyunix.core.Hls.duration:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ziyunix_core_hls_proto_init() }
func file_ziyunix_core_hls_proto_init() {
	if File_ziyunix_core_hls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ziyunix_core_hls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ziyunix_core_hls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ziyunix_core_hls_proto_goTypes,
		DependencyIndexes: file_ziyunix_core_hls_proto_depIdxs,
		MessageInfos:      file_ziyunix_core_hls_proto_msgTypes,
	}.Build()
	File_ziyunix_core_hls_proto = out.File
	file_ziyunix_core_hls_proto_rawDesc = nil
	file_ziyunix_core_hls_proto_goTypes = nil
	file_ziyunix_core_hls_proto_depIdxs = nil
}
