// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: ziyunix/core/watermark.proto

package core

import (
	transfer "github.com/storezhang/transfer"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频
type Watermark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 类型
	Type WatermarkType `protobuf:"varint,3,opt,name=type,proto3,enum=ziyunix.core.WatermarkType" json:"type,omitempty"`
	// 文件
	// @gotags: validate:"required"
	File *transfer.File `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty" validate:"required"`
}

func (x *Watermark) Reset() {
	*x = Watermark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ziyunix_core_watermark_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watermark) ProtoMessage() {}

func (x *Watermark) ProtoReflect() protoreflect.Message {
	mi := &file_ziyunix_core_watermark_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watermark.ProtoReflect.Descriptor instead.
func (*Watermark) Descriptor() ([]byte, []int) {
	return file_ziyunix_core_watermark_proto_rawDescGZIP(), []int{0}
}

func (x *Watermark) GetType() WatermarkType {
	if x != nil {
		return x.Type
	}
	return WatermarkType_WATERMARK_TYPE_UNSPECIFIED
}

func (x *Watermark) GetFile() *transfer.File {
	if x != nil {
		return x.File
	}
	return nil
}

var File_ziyunix_core_watermark_proto protoreflect.FileDescriptor

var file_ziyunix_core_watermark_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x7a, 0x69, 0x79, 0x75, 0x6e, 0x69, 0x78, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x77,
	0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x7a, 0x69, 0x79, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x7a, 0x69,
	0x79, 0x75, 0x6e, 0x69, 0x78, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6b, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x2f, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x7a, 0x69, 0x79,
	0x75, 0x6e, 0x69, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d,
	0x61, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x32, 0x0a, 0x10,
	0x63, 0x6f, 0x6d, 0x2e, 0x7a, 0x69, 0x79, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x50, 0x01, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a,
	0x69, 0x79, 0x75, 0x6e, 0x69, 0x78, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ziyunix_core_watermark_proto_rawDescOnce sync.Once
	file_ziyunix_core_watermark_proto_rawDescData = file_ziyunix_core_watermark_proto_rawDesc
)

func file_ziyunix_core_watermark_proto_rawDescGZIP() []byte {
	file_ziyunix_core_watermark_proto_rawDescOnce.Do(func() {
		file_ziyunix_core_watermark_proto_rawDescData = protoimpl.X.CompressGZIP(file_ziyunix_core_watermark_proto_rawDescData)
	})
	return file_ziyunix_core_watermark_proto_rawDescData
}

var file_ziyunix_core_watermark_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ziyunix_core_watermark_proto_goTypes = []interface{}{
	(*Watermark)(nil),     // 0: ziyunix.core.Watermark
	(WatermarkType)(0),    // 1: ziyunix.core.WatermarkType
	(*transfer.File)(nil), // 2: storezhang.transfer.File
}
var file_ziyunix_core_watermark_proto_depIdxs = []int32{
	1, // 0: ziyunix.core.Watermark.type:type_name -> ziyunix.core.WatermarkType
	2, // 1: ziyunix.core.Watermark.file:type_name -> storezhang.transfer.File
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ziyunix_core_watermark_proto_init() }
func file_ziyunix_core_watermark_proto_init() {
	if File_ziyunix_core_watermark_proto != nil {
		return
	}
	file_ziyunix_core_watermark_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ziyunix_core_watermark_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watermark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ziyunix_core_watermark_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ziyunix_core_watermark_proto_goTypes,
		DependencyIndexes: file_ziyunix_core_watermark_proto_depIdxs,
		MessageInfos:      file_ziyunix_core_watermark_proto_msgTypes,
	}.Build()
	File_ziyunix_core_watermark_proto = out.File
	file_ziyunix_core_watermark_proto_rawDesc = nil
	file_ziyunix_core_watermark_proto_goTypes = nil
	file_ziyunix_core_watermark_proto_depIdxs = nil
}
